environment:
  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.5
      PYTHON_ARCH: "64"

install:
  - python --version
  - pip install -r requirements.txt

build_script:
  - echo "Hello world"

