#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # ...
elif [[ "$OSTYPE" == "darwin"* ]]; then
    pip3 --version
    python3 --version
    pip3 install -r requirements.txt
    PYGEODESY_PATH=$(python3 -c "import pygeodesy; print(pygeodesy.__path__[0])")
    cd PySoar
    pyinstaller --windowed --paths=$PYGEODESY_PATH main_pysoar.py
    cp -r dist/main_pysoar.app .
    zip -r dist/mac_pysoar.zip main_pysoar.app
elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
elif [[ "$OSTYPE" == "msys" ]]; then
        # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
elif [[ "$OSTYPE" == "win32" ]]; then
        # I'm not sure this can happen.
elif [[ "$OSTYPE" == "freebsd"* ]]; then
        # ...
else
        # Unknown.
fi
