#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo "this is linux-gnu"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "this is mac"
    pip3 --version
    python3 --version
    pip3 install attrdict3
    pip3 install -r requirements.txt
    cd PySoar
    pyinstaller --windowed main_pysoar.py
    cp -r dist/main_pysoar.app .
    zip -r dist/mac_pysoar.zip main_pysoar.app
elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo "this is cygwin"
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "this is msys"
    choco install python3 --version=3.8.15 --force
    choco install 7zip.install --force
    export PATH="/c/Python37:/c/Python37/Scripts:/c/Python38:/c/Python38/Scripts:$PATH"
    python --version
    pip --version
    pip install attrdict3
    pip install -r requirements.txt
    cd PySoar
    pyinstaller --onefile --windowed main_pysoar.py
    cp dist/main_pysoar.exe .
    7z a dist/windows_pysoar.zip main_pysoar.exe
elif [[ "$OSTYPE" == "win32" ]]; then
    echo "this is windows"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo "this is freebsd"
else
    echo "this is unknown"
fi
